In [66]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import re
import unidecode
import os

#### Carga de fichero

In [67]:
os.getcwd()
os.listdir('.')

['economia_comercio_bancos_2019.csv',
 '.ipynb_checkpoints',
 'Mastersheet.csv',
 'fichero_municipios.ipynb',
 'sociedad_sanidad_hospitales_2019.csv']

In [68]:
#df = pd.read_csv("C:\\Users\\pmari\\saturdaysai\\proyecto\\Exodus_urbano\\data\\Guille\\MasterSheet.csv")
df = pd.read_csv("../Guille/Mastersheet.csv")

In [69]:
df

       Postal code           Cities     Province Autonomous Community
0             1001  Vitoria-Gasteiz  Áraba/Álava           País Vasco
1             1002  Vitoria-Gasteiz  Áraba/Álava           País Vasco
2             1003  Vitoria-Gasteiz  Áraba/Álava           País Vasco
3             1004  Vitoria-Gasteiz  Áraba/Álava           País Vasco
4             1005  Vitoria-Gasteiz  Áraba/Álava           País Vasco
...            ...              ...          ...                  ...
11131        48000            Bilbo      Bizkaia           País Vasco
11132        49000              NaN       Zamora      Castilla y León
11133        50000              NaN     Zaragoza               Aragón
11134        51000              NaN        Ceuta                Ceuta
11135        52000              NaN      Melilla              Melilla

[11136 rows x 4 columns]

In [70]:
df.dtypes

Postal code              int64
Cities                  object
Province                object
Autonomous Community    object
dtype: object

#### Limipieza

In [71]:
df_nulls = df[df['Cities'].isnull()]
df_nulls.head()

     Postal code Cities  Province  Autonomous Community
148         2359    NaN  Albacete    Castilla La Mancha
239         3149    NaN  Alicante  Comunidad Valenciana
246         3176    NaN  Alicante  Comunidad Valenciana
291         3319    NaN  Alicante  Comunidad Valenciana
293         3321    NaN  Alicante  Comunidad Valenciana

##### Relleno de nulls en el campo Cities

In [72]:
df.fillna('', inplace=True)

In [73]:
def doClean(text):   
    
    # Quitar las expresiones tras la barra /
    a = re.sub('\/.*', '', text)
    # Quitar las aclaraciones entre paréntesis
    a = re.sub('\(.*\)', '', a)
    # Quitar acentos 
    a = unidecode.unidecode(a)
    # Quitar aquello que no sean palabras o cosa que se le parezca
    a = re.sub('\W', ' ', a) 
    # Quitar espacios extra en caso de haber
    a = re.sub('\s+', ' ', a)
    # Pasar el texto a minúsulas
    a = a.lower() 
    a = re.sub(' ', '_', a)
    #a = a.strip() 
    
    return a

##### Limpieza campos categoricos

In [83]:
df['municipio'] = df['Cities'].apply(doClean)

In [84]:
df.head()

,Postal code,Cities,Province,Autonomous Community,municipio_limpio,provincia,ccaa,cp,municipio
0,1001,Vitoria-Gasteiz,Áraba/Álava,País Vasco,vitoria_gasteiz,araba,pais_vasco,1001,vitoria_gasteiz
1,1002,Vitoria-Gasteiz,Áraba/Álava,País Vasco,vitoria_gasteiz,araba,pais_vasco,1002,vitoria_gasteiz
2,1003,Vitoria-Gasteiz,Áraba/Álava,País Vasco,vitoria_gasteiz,araba,pais_vasco,1003,vitoria_gasteiz
3,1004,Vitoria-Gasteiz,Áraba/Álava,País Vasco,vitoria_gasteiz,araba,pais_vasco,1004,vitoria_gasteiz
4,1005,Vitoria-Gasteiz,Áraba/Álava,País Vasco,vitoria_gasteiz,araba,pais_vasco,1005,vitoria_gasteiz

In [85]:
df['provincia'] = df['Province'].apply(doClean)

In [86]:
df['ccaa'] = df['Autonomous Community'].apply(doClean)

In [87]:
df.head()

,Postal code,Cities,Province,Autonomous Community,municipio_limpio,provincia,ccaa,cp,municipio
0,1001,Vitoria-Gasteiz,Áraba/Álava,País Vasco,vitoria_gasteiz,araba,pais_vasco,1001,vitoria_gasteiz
1,1002,Vitoria-Gasteiz,Áraba/Álava,País Vasco,vitoria_gasteiz,araba,pais_vasco,1002,vitoria_gasteiz
2,1003,Vitoria-Gasteiz,Áraba/Álava,País Vasco,vitoria_gasteiz,araba,pais_vasco,1003,vitoria_gasteiz
3,1004,Vitoria-Gasteiz,Áraba/Álava,País Vasco,vitoria_gasteiz,araba,pais_vasco,1004,vitoria_gasteiz
4,1005,Vitoria-Gasteiz,Áraba/Álava,País Vasco,vitoria_gasteiz,araba,pais_vasco,1005,vitoria_gasteiz

In [101]:
df['cp'] = df['Postal code'].apply("{:05d}".format)

##### Eliminación de duplicados

In [103]:
df[df.duplicated(subset=['cp', 'municipio', 'provincia', 'ccaa'])]

,Postal code,Cities,Province,Autonomous Community,municipio_limpio,provincia,ccaa,cp,municipio
100,2140,Albacete,Albacete,Castilla La Mancha,albacete,albacete,castilla_la_mancha,02140,albacete
237,3139,Elx/Elche,Alicante,Comunidad Valenciana,elx,alicante,comunidad_valenciana,03139,elx
1771,10195,Cáceres,Cáceres,Extremadura,caceres,caceres,extremadura,10195,caceres
2041,11405,Jerez de la Frontera,Cádiz,Andalucía,jerez_de_la_frontera,cadiz,andalucia,11405,jerez_de_la_frontera
4088,22583,Arén,Huesca,Aragón,aren,huesca,aragon,22583,aren
4090,22584,Puente de Montañana,Huesca,Aragón,puente_de_montanana,huesca,aragon,22584,puente_de_montanana
4156,22808,Agüero,Huesca,Aragón,aguero,huesca,aragon,22808,aguero
5102,26212,Miranda de Ebro,La Rioja,La Rioja,miranda_de_ebro,la_rioja,la_rioja,26212,miranda_de_ebro
6077,29590,Málaga,Málaga,Andalucía,malaga,malaga,andalucia,29590,malaga
6079,29591,Málaga,Málaga,Andalucía,malaga,malaga,andalucia,29591,malaga
7104,33554,Cabrales,Asturias,Principado de Asturias,cabrales,asturias,principado_de_asturias,33554,cabrales
8559,39232,Alfoz de Bricia,Cantabria,Cantabria,alfoz_de_bricia,cantabria,cantabria,39232,alfoz_de_bricia
9170,42269,Arcos de Jalón,Soria,Castilla y León,arcos_de_jalon,soria,castilla_y_leon,42269,arcos_de_jalon
9229,43206,Reus,Tarragona,Catalunya,reus,tarragona,catalunya,43206,reus
9572,44591,Vinaceite,Teruel,Aragón,vinaceite,teruel,aragon,44591,vinaceite

In [104]:
maestro_municipios = df[['cp', 'municipio', 'provincia', 'ccaa']].drop_duplicates()

##### Creación y exportación de fichero maestro

In [105]:
maestro_municipios.head()

      cp        municipio provincia        ccaa
0  01001  vitoria_gasteiz     araba  pais_vasco
1  01002  vitoria_gasteiz     araba  pais_vasco
2  01003  vitoria_gasteiz     araba  pais_vasco
3  01004  vitoria_gasteiz     araba  pais_vasco
4  01005  vitoria_gasteiz     araba  pais_vasco

In [106]:
maestro_municipios.to_csv("maestro_municipios.csv")