In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import re
import unidecode
import os

#### Funciones

In [28]:
def doClean(a):   
    a = str(a)
    # Quitar las expresiones tras la barra /
    #a = re.sub('\/.*', '', a)
    # Quitar las aclaraciones entre paréntesis
    a = re.sub('\(.*\)', '', a)
    # Quitar acentos 
    a = unidecode.unidecode(a)
    # Quitar aquello que no sean palabras o cosa que se le parezca
    a = re.sub('\W', ' ', a) 
    # Quitar espacios extra en caso de haber
    a = re.sub('\s+', ' ', a)
    # Pasar el texto a minúsulas
    a = a.lower() 
    # Quitar espacio izq
    a = a.lstrip()
    # Quitar espacio derecha
    a = a.rstrip()
    a = re.sub(' ', '_', a)
    #a = a.strip() 
    
    return a

#### Carga de ficheros

In [29]:
os.getcwd()

'/home/patcalsi/projects/Exodus_urbano/data/patri'

In [73]:
establecimientos = pd.read_excel("Empresas-SICTED2.xls", dtype={'Cód postal':object})

In [74]:
establecimientos.shape

(9175, 19)

In [75]:
establecimientos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9175 entries, 0 to 9174
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Destino             9175 non-null   object
 1   Establecimiento     9175 non-null   object
 2   Oficio              9175 non-null   object
 3   Unnamed: 3          0 non-null      float64
 4   Localidad           8980 non-null   object
 5   Comunidad autónoma  9175 non-null   object
 6   Dirección           8980 non-null   object
 7   Unnamed: 7          0 non-null      float64
 8   Cód postal          8980 non-null   object
 9   Unnamed: 9          0 non-null      float64
 10  Correo Electrónico  8922 non-null   object
 11  Teléfono            9175 non-null   object
 12  Dir. WEB            3766 non-null   object
 13  Facebook            2204 non-null   object
 14  Twiter              1144 non-null   object
 15  Unnamed: 15         0 non-null      float64
 16  Unnamed: 16         0 non-null      float64
 17  Blogger             298 non-null    object
 18  Youtube             631 non-null    object
dtypes: float64(5), object(14)
memory usage: 1.3+ MB

In [76]:
establecimientos.head()

,Destino,Establecimiento,Oficio,Unnamed: 3,Localidad,Comunidad autónoma,Dirección,Unnamed: 7,Cód postal,Unnamed: 9,Correo Electrónico,Teléfono,Dir. WEB,Facebook,Twiter,Unnamed: 15,Unnamed: 16,Blogger,Youtube
0,Águilas,APARTAMENTOS TURÍSTICOS ÁGUILAS DE LOS COLLADOS,Hoteles y apartamentos turísticos,NaN,ÁGUILAS,Región de Murcia,Ctra Calabardina s/n,NaN,30880,NaN,rservas@aguilasdeloscollados.com,968419100,www.aguilasdeloscollados.com,NaN,NaN,NaN,NaN,NaN,NaN
1,Águilas,AUDITORIO Y PALACIO DE CONGRESOS INFANTA DOÑA ...,Palacios de congresos,NaN,Águilas,Región de Murcia,C/ Aire Nº 153,NaN,30880,NaN,auditorio@ayuntamientodeaguilas.org,968413771,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Águilas,CAFÉ BAR BAMBOO,Bares y cafeterías,NaN,Águilas,Región de Murcia,"PLAZA GUTIÉRREZ MELLADO, 2",NaN,30880,NaN,comicoctel@hotmail.com,868975067,NaN,CAFE BAR BAMBOO,NaN,NaN,NaN,NaN,CAFEBAMBOOOK
3,Águilas,CAMPING BELLAVISTA,Campings,NaN,Águilas,Región de Murcia,"CTRA. DE VERA, KM.3",NaN,30880,NaN,info@campingbellavista.com,620260108,www.campingbellavista.com,https://www.facebook.com/pages/Camping-BellaVi...,https://twitter.com/CAMPBELLAVISTA,NaN,NaN,NaN,https://www.youtube.com/channel/UCnzXRHg4Tgjqm...
4,Águilas,Capiola Viajes,Agencias de viajes,NaN,Águilas,Región de Murcia,C/ Mercado 4,NaN,30880,NaN,molinatina@hotmail.es,968414126,NaN,Capiola Viajes,Capiola Viajes,NaN,NaN,NaN,NaN

In [77]:
establecimientos.nunique()

Destino                178
Establecimiento       9070
Oficio                  32
Unnamed: 3               0
Localidad             1798
Comunidad autónoma      18
Dirección             7894
Unnamed: 7               0
Cód postal            1523
Unnamed: 9               0
Correo Electrónico    7325
Teléfono              7699
Dir. WEB              3349
Facebook              2057
Twiter                1034
Unnamed: 15              0
Unnamed: 16              0
Blogger                270
Youtube                552
dtype: int64

In [78]:
establecimientos.isnull().sum()

Destino                  0
Establecimiento          0
Oficio                   0
Unnamed: 3            9175
Localidad              195
Comunidad autónoma       0
Dirección              195
Unnamed: 7            9175
Cód postal             195
Unnamed: 9            9175
Correo Electrónico     253
Teléfono                 0
Dir. WEB              5409
Facebook              6971
Twiter                8031
Unnamed: 15           9175
Unnamed: 16           9175
Blogger               8877
Youtube               8544
dtype: int64

##### tratamiento

In [79]:
establecimientos['municipio_limpio'] = establecimientos['Localidad'].apply(doClean)

In [80]:
establecimientos['ccaa'] = establecimientos['Comunidad autónoma'].apply(doClean)

In [81]:
establecimientos['codigo_postal'] = establecimientos['Cód postal']

In [82]:
establecimientos.head(2)

,Destino,Establecimiento,Oficio,Unnamed: 3,Localidad,Comunidad autónoma,Dirección,Unnamed: 7,Cód postal,Unnamed: 9,...,Dir. WEB,Facebook,Twiter,Unnamed: 15,Unnamed: 16,Blogger,Youtube,municipio_limpio,ccaa,codigo_postal
0,Águilas,APARTAMENTOS TURÍSTICOS ÁGUILAS DE LOS COLLADOS,Hoteles y apartamentos turísticos,NaN,ÁGUILAS,Región de Murcia,Ctra Calabardina s/n,NaN,30880,NaN,...,www.aguilasdeloscollados.com,NaN,NaN,NaN,NaN,NaN,NaN,aguilas,region_de_murcia,30880
1,Águilas,AUDITORIO Y PALACIO DE CONGRESOS INFANTA DOÑA ...,Palacios de congresos,NaN,Águilas,Región de Murcia,C/ Aire Nº 153,NaN,30880,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,aguilas,region_de_murcia,30880

In [83]:
establecimientos[establecimientos['municipio_limpio']=='segorbe'].head(2)

,Destino,Establecimiento,Oficio,Unnamed: 3,Localidad,Comunidad autónoma,Dirección,Unnamed: 7,Cód postal,Unnamed: 9,...,Dir. WEB,Facebook,Twiter,Unnamed: 15,Unnamed: 16,Blogger,Youtube,municipio_limpio,ccaa,codigo_postal
7564,Segorbe,Alojamientos rurales La Belluga,Alojamientos rurales,NaN,Segorbe,Comunitat Valenciana,"Calle Augusto, 1",NaN,12400,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,segorbe,comunitat_valenciana,12400
7565,Segorbe,Apartamentos El Olivo,Alojamientos rurales,NaN,Segorbe,Comunitat Valenciana,"Av. España, 125 Ático 13",NaN,12400,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,segorbe,comunitat_valenciana,12400

In [84]:
establecimientos = establecimientos.groupby(by=['codigo_postal', 'municipio_limpio', 'ccaa', 'Oficio'], as_index=False)['Establecimiento'].count()

In [85]:
establecimientos.head(5)

,codigo_postal,municipio_limpio,ccaa,Oficio,Establecimiento
0,00000,aldea_de_cuenca_hinojares,andalucia,Hoteles y apartamentos turísticos,1
1,00000,arroyo_frio_la_iruela,andalucia,Empresas de turismo activo,1
2,00000,arroyo_frio_la_iruela,andalucia,Restaurantes y empresas turísticas de Catering,1
3,00000,cazorla,andalucia,Bares y cafeterías,1
4,00000,cazorla,andalucia,Comercios,1

In [86]:
establecimientos = establecimientos.pivot_table(index=['codigo_postal', 'municipio_limpio', 'ccaa'], columns='Oficio',  values=['Establecimiento'], aggfunc='sum').reset_index()

In [87]:
establecimientos.head()

       codigo_postal           municipio_limpio       ccaa    Establecimiento  \
Oficio                                                     Agencias de viajes
0              00000  aldea_de_cuenca_hinojares  andalucia                NaN
1              00000      arroyo_frio_la_iruela  andalucia                NaN
2              00000                    cazorla  andalucia                NaN
3              00000                  la_iruela  andalucia                NaN
4              00000                 pozo_alcon  andalucia                NaN

                                                                               \
Oficio Albergues Alojamientos rurales Artesanos Atraque de cruceros y ferries
0            NaN                  NaN       NaN                           NaN
1            NaN                  NaN       NaN                           NaN
2            NaN                  NaN       NaN                           NaN
3            1.0                  NaN       NaN                           NaN
4            1.0                  3.0       NaN                           NaN

                                   ...                                        \
Oficio Bares y cafeterías Bodegas  ... Otros Servicios Palacios de congresos
0                     NaN     NaN  ...             NaN                   NaN
1                     NaN     NaN  ...             NaN                   NaN
2                     1.0     NaN  ...             NaN                   NaN
3                     NaN     NaN  ...             NaN                   NaN
4                     NaN     NaN  ...             NaN                   NaN

                                  \
Oficio Playas Puertos Deportivos
0         NaN                NaN
1         NaN                NaN
2         NaN                NaN
3         NaN                NaN
4         NaN                NaN

                                                                           \
Oficio Restaurantes y empresas turísticas de Catering Seguridad ciudadana
0                                                 NaN                 NaN
1                                                 1.0                 NaN
2                                                 NaN                 NaN
3                                                 NaN                 NaN
4                                                 NaN                 NaN

                                                                  \
Oficio Servicios de limpieza Servicios turísticos de salud Taxis
0                        NaN                           NaN   NaN
1                        NaN                           NaN   NaN
2                        NaN                           NaN   NaN
3                        NaN                           NaN   NaN
4                        NaN                           NaN   NaN


Oficio Turismo Industrial
0                     NaN
1                     NaN
2                     NaN
3                     NaN
4                     NaN

[5 rows x 35 columns]

In [88]:
def standardize_headers(x):
    return x.replace(' ', '_').lower()

establecimientos = establecimientos.rename(columns=standardize_headers)

In [93]:
establecimientos.columns = establecimientos.columns.droplevel()

In [95]:
establecimientos.columns

Index(['', '', '', 'agencias_de_viajes', 'albergues', 'alojamientos_rurales',
       'artesanos', 'atraque_de_cruceros_y_ferries', 'bares_y_cafeterías',
       'bodegas', 'campings', 'campos_de_golf_y_campos_de_pitch&putt',
       'comercios', 'convention_bureaux',
       'empresas_de_alquiler_de_vehículos_y_embarcaciones',
       'empresas_de_transporte_turístico', 'empresas_de_turismo_activo',
       'escuelas_de_español_para_extranjeros', 'espacios_naturales_protegidos',
       'estaciones_de_esquí_y_montaña', 'guías_turísticos',
       'hoteles_y_apartamentos_turísticos',
       'museos_y_centros_de_interés_turístico_visitable', 'opc's',
       'oficinas_de_información_turística', 'otros_servicios',
       'palacios_de_congresos', 'playas', 'puertos_deportivos',
       'restaurantes_y_empresas_turísticas_de_catering', 'seguridad_ciudadana',
       'servicios_de_limpieza', 'servicios_turísticos_de_salud', 'taxis',
       'turismo_industrial'],
      dtype='object', name='Oficio')

In [97]:
establecimientos.columns = ['codigo_postal', 'municipio_limpio', 'ccaa', 'agencias_de_viajes', 'albergues', 'alojamientos_rurales',
       'artesanos', 'atraque_de_cruceros_y_ferries', 'bares_y_cafeterías',
       'bodegas', 'campings', 'campos_de_golf_y_campos_de_pitch&putt',
       'comercios', 'convention_bureaux',
       'empresas_de_alquiler_de_vehículos_y_embarcaciones',
       'empresas_de_transporte_turístico', 'empresas_de_turismo_activo',
       'escuelas_de_español_para_extranjeros', 'espacios_naturales_protegidos',
       'estaciones_de_esquí_y_montaña', 'guías_turísticos',
       'hoteles_y_apartamentos_turísticos',
       'museos_y_centros_de_interés_turístico_visitable', 'opc',
       'oficinas_de_información_turística', 'otros_servicios',
       'palacios_de_congresos', 'playas', 'puertos_deportivos',
       'restaurantes_y_empresas_turísticas_de_catering', 'seguridad_ciudadana',
       'servicios_de_limpieza', 'servicios_turísticos_de_salud', 'taxis',
       'turismo_industrial']

In [98]:
establecimientos.shape

(2063, 35)

In [99]:
establecimientos[establecimientos.duplicated(subset=['municipio_limpio', 'ccaa'])]

,codigo_postal,municipio_limpio,ccaa,agencias_de_viajes,albergues,alojamientos_rurales,artesanos,atraque_de_cruceros_y_ferries,bares_y_cafeterías,bodegas,...,otros_servicios,palacios_de_congresos,playas,puertos_deportivos,restaurantes_y_empresas_turísticas_de_catering,seguridad_ciudadana,servicios_de_limpieza,servicios_turísticos_de_salud,taxis,turismo_industrial
8,01002,vitoria_gasteiz,euskadi_pais_vasco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,01003,vitoria_gasteiz,euskadi_pais_vasco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,01007,vitoria_gasteiz,euskadi_pais_vasco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,01008,vitoria_gasteiz,euskadi_pais_vasco,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
12,01009,vitoria_gasteiz,euskadi_pais_vasco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2053,50580,vera_de_moncayo,aragon,NaN,NaN,2.0,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2059,50591,anon_de_moncayo,aragon,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2060,51001,ceuta,ciudad_autonoma_de_ceuta,4.0,NaN,NaN,NaN,2.0,13.0,NaN,...,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,3.0,1.0
2061,51002,ceuta,ciudad_autonoma_de_ceuta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,NaN
2062,51004,ceuta,ciudad_autonoma_de_ceuta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [100]:
establecimientos.drop_duplicates(subset=['codigo_postal', 'municipio_limpio', 'ccaa'], inplace=True)

In [101]:
establecimientos.shape

(2063, 35)

##### Creación y exportación de fichero maestro

In [102]:
establecimientos.head()

,codigo_postal,municipio_limpio,ccaa,agencias_de_viajes,albergues,alojamientos_rurales,artesanos,atraque_de_cruceros_y_ferries,bares_y_cafeterías,bodegas,...,otros_servicios,palacios_de_congresos,playas,puertos_deportivos,restaurantes_y_empresas_turísticas_de_catering,seguridad_ciudadana,servicios_de_limpieza,servicios_turísticos_de_salud,taxis,turismo_industrial
0,00000,aldea_de_cuenca_hinojares,andalucia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,00000,arroyo_frio_la_iruela,andalucia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
2,00000,cazorla,andalucia,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,00000,la_iruela,andalucia,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00000,pozo_alcon,andalucia,NaN,1.0,3.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [103]:
establecimientos.to_csv("economia_turismo_establecimientos_20??_limpio.csv")